---
- name: Install packages
  when: cansudo is not changed
  apt:
    pkg:
    - vim
    - curl
    - wget
    - keepassxc
    - git
    - thrift-compiler
    state: present
  register: out    
  become: yes
  
- debug: var=out.stdout_lines

- name: setup git block
  blockinfile: 
    path: "{{ profile_path }}"
    state: present
    marker: "# {mark} Ansible Managed git prompt"
    block: "{{ lookup('template', 'gitprompt.j2') }}"

- name: Add aliases to profile
  blockinfile:  
    path: "{{ profile_path }}"
    state: present
    marker: "# {mark} Ansible Managed aliases"    
    block: "{{ lookup('template', 'aliases.j2') }}"

