- name: "Setup docker ubuntu or debian"
  hosts: localhost
  connection: local
  gather_facts: yes
  tags: crc  

  roles:
    - role: crc
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'