---
- name: Remove minikube
  become: true
  apt:
    pkg: minikube
    state: absent
    purge: yes   
  register: out

- name: Remove old Minikube
  file:
    path: "{{ minikube_tmp_file }}"
    state: absent
  register: out  

- name: Download Minikube
  uri:
    url: "{{ minikube_url }}"
    dest: "{{ minikube_tmp_file }}"    
    follow_redirects: all
    force: true
  register: out  


- name: Install Minikube
  become: true
  apt:
    deb: "{{ minikube_tmp_file }}"
    state: present
  register: out

- name: Print out
  debug: var=out  


    