---
- name: Install JDK 11
  apt:
    pkg:
    - openjdk-11-jdk-headless
    - openjdk-11-source
    - maven
    state: present
  become: yes

- name: fetch maven home
  shell: update-alternatives --display mvn | grep "currently" | sed -n 's/.* \(\/.*\)\/bin\/.*/\1/p'
  register: mavendir
- debug: var=mavendir.stdout_lines

- name: fetch java home
  shell: update-alternatives --display javac | grep "currently" | sed -n 's/.* \(\/.*\)\/bin\/java.*/\1/p'
  register: javahomedir
- debug: var=javahomedir.stdout_lines

- set_fact: 
    javahomedir={{ javahomedir.stdout }}

- name: Check JAVA_HOME is set
  lineinfile: 
    path: ~/.profile
    state: present
    regexp: '^JAVA_HOME='
    line: "JAVA_HOME={{ javahomedir }}"
  register: profile  

- name: source profile
  shell: . ~/.profile
  when: profile.changed
