---
- name: add ssh directory
  file:
    path=/home/{{ ansible_user }}/.ssh
    state=directory
    mode=0700
    owner={{ ansible_user }}
    group={{ ansible_user|default(ansible_user)  }}
  register: out  

- name: add ssh authorized_keys
  file:
    path=/home/{{ ansible_user }}/.ssh/authorized_keys
    state=touch
    mode=0644
    owner={{ ansible_user }}
    group={{ ansible_user|default(ansible_user)  }}
  register: out


- name: add ssh config
  file:
    path=/home/{{ ansible_user }}/.ssh/config
    state=touch
    mode=0644
    owner={{ ansible_user }}
    group={{ ansible_user|default(ansible_user)  }}
  register: out  
    

- name: upgrade apt
  apt:
    upgrade: dist
  register: out  
  become: yes

- name: clean apt
  apt:
    autoclean: yes
  register: out  
  become: yes  

- name: remove apt
  apt:
    autoremove: yes    
  register: out
  become: yes      


