---
- name: Check if sudoers don't require password
  lineinfile: 
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: yes
  register: cansudo

- name: Apt update
  apt: 
    name: "*"
    state: latest
  become: yes
  notify: 
    - upgrade apt
    - clean apt
    - remove apt 
  when: cansudo is not changed

- meta: flush_handlers  

- name: Install packages
  apt:
    pkg:
    - vim
    - curl
    - wget
    - keepassxc
    - git
    - thrift-compiler
    state: present
  become: yes
  when: cansudo is not changed

- name: Check if ssh exists
  stat:
    path: ~/.ssh
  notify:
    - add ssh directory
    - add ssh authorized_keys
    - add ssh config
  register: ssh_details 
  changed_when:
    - ssh_details.stat.exists == False 

- debug: 
    msg: The file {{ ssh_details.stat.path  }} exists is {{ ssh_details.stat.exists  }}

- meta: flush_handlers      



