---
- name: Check if sudoers don't require password
  lineinfile: 
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: yes
  register: cansudo

- name: Apt update
  when: cansudo is not changed
  apt: 
    name: "*"
    state: latest
  become: yes
  notify: 
    - upgrade apt
    - clean apt
    - remove apt 
    
- meta: flush_handlers  

- name: Check if ssh exists
  stat:
    path: ~/.ssh
  notify:
    - add ssh directory
    - add ssh authorized_keys
  register: ssh_details 
  changed_when:
    - ssh_details.stat.exists == False 

- debug: 
    msg: The file {{ ssh_details.stat.path  }} exists is {{ ssh_details.stat.exists  }}

- meta: flush_handlers      

- name: Check ssh config exist
  stat:
    path: ~/.ssh/config
  notify:
    - add ssh config
  register: ssh_details 
  changed_when:
    - ssh_details.stat.exists == False 

- meta: flush_handlers      

- name: Add ssh config
  blockinfile:  
    path: "/home/{{ ansible_user }}/.ssh/config"
    state: present
    marker: "# {mark} Ansible Managed config"    
    block: "{{ lookup('template', 'config.j2') }}"    
