---
- name: Check if sudoers don't require password
  lineinfile: 
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: yes

- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    name: "*"
    update_cache: yes
    cache_valid_time: 3600
  become: yes  

- name: Update all packages to the latest version
  apt:
    upgrade: dist
  become: yes  

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  become: yes  

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes    
  become: yes  

- name: Install packages
  apt:
    pkg:
    - vim
    - curl
    - wget
    - keepassxc
    - git
    state: present
  become: yes
