---
- name: Check if sudoers don't require password
  lineinfile: 
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: yes
  register: cansudo

- name: Apt update
  when: cansudo is not changed
  apt: 
    name: "*"
    state: latest
  become: yes
  notify: 
    - upgrade apt
    - clean apt
    - remove apt 
    
- meta: flush_handlers  

- name: Install packages
  when: cansudo is not changed
  apt:
    pkg:
    - vim
    - curl
    - wget
    - keepassxc
    - git
    - thrift-compiler
    state: present
  become: yes
  

- name: Check if ssh exists
  stat:
    path: ~/.ssh
  notify:
    - add ssh directory
    - add ssh authorized_keys
    - add ssh config
  register: ssh_details 
  changed_when:
    - ssh_details.stat.exists == False 

- debug: 
    msg: The file {{ ssh_details.stat.path  }} exists is {{ ssh_details.stat.exists  }}

- meta: flush_handlers      


- name: setup git block
  blockinfile: 
    path: "{{ profile_path }}"
    state: present
    marker: "# {mark} Ansible Managed git prompt"
    block: | 
      parse_git_branch() {
        git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
      }
      PS1="\u@\h \[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "



