---
- name: setup git block
  blockinfile: 
    path: "{{ profile_path }}"
    state: present
    marker: "# {mark} Ansible Managed git prompt"
    block: "{{ lookup('template', 'gitprompt.j2') }}"

- name: Add aliases to profile
  blockinfile:  
    path: "{{ profile_path }}"
    state: present
    marker: "# {mark} Ansible Managed aliases"    
    block: "{{ lookup('template', 'aliases.j2') }}"


- import_tasks: flutter.yml

- import_tasks: android-install.yml

- import_tasks: android-configure.yml
